version: "3.3"

services:

  database:
    build:
      context: .
      dockerfile: postgres-Dockerfile
    environment:
      POSTGRES_DB: pzero_db
      POSTGRES_USER: pzero
      POSTGRES_PASSWORD: pzero
      TZ: Europe/Warsaw
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - main

networks:
  main:

volumes:
  database_data: